import Navbar from "@/components/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { gabarito } from "@/assets/fonts";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Anak Front-End",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={gabarito.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
